---
- name: "Check Status"
  hosts: localhost
  gather_facts: no

  tasks:
  - name: status
    redhat.satellite.status_info:
      server_url: "{{ sat_url }}"
      username: "sat-admin"
      password: "emergent"
      validate_certs: no