---

- name: "Install connected satellite server"
  hosts: all
  become: yes
  gather_facts: no
  vars:
    sub_name: "Red Hat Enterprise Linux"
    product: "Red Hat Enterprise Linux for x86_64"
    organization: "Emergent"
    cv_name: "cv_rhel8_base"
    content_repos:
      - set_name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)"
        synch_name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8"
      - set_name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)"
        synch_name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8"
      - set_name: "Red Hat Satellite Tools 6.10 for RHEL 8 x86_64 (RPMs)"
        synch_name: "Red Hat Satellite Tools 6.10 for RHEL 8 x86_64 RPMs"
    lifecycle_envs:
      - name: Development
        prior: Library
      - name: Testing
        prior: Development
      - name: Production
        prior: Testing
    ak_prod:
      name: rhel8_prod
      cv: RHEL8
      lc: Production

  tasks:
  - name: "set content repositories"
    include_tasks: set_repos.yml
    loop: "{{ content_repos }}"

  - name: "synch content repositories"
    include_tasks: synch_content_repos.yml
    loop: "{{ content_repos }}"

  - name: "create lifecycle environments"
    include_tasks: set_lifecycle_envs.yml
    loop: "{{ lifecycle_envs }}"

