---

- name: "Configure connected satellite server"
  hosts: all
  become: yes
  gather_facts: no
  vars:
    sub_name: "Red Hat Enterprise Linux"
    product: "Red Hat Enterprise Linux for x86_64"
    organization: "Emergent"
    cv_name: "cv_rhel8_base"
    content_repos:
      - set_name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)"
        synch_name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8"
      - set_name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)"
        synch_name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8"
      - set_name: "Red Hat Satellite Tools 6.10 for RHEL 8 x86_64 (RPMs)"
        synch_name: "Red Hat Satellite Tools 6.10 for RHEL 8 x86_64 RPMs"
    lifecycle_envs:
      - name: Development
        prior: Library
      - name: Testing
        prior: Development
      - name: Production
        prior: Testing
    ak_prod:
      name: rhel8_prod
      cv: RHEL8
      lc: Production
    first_filter:
      - name: "all packages without errata"
        content_type: "package"
        inclusion_type: "true"
        original_packages: "true"
    second_filter:
      - name: "Errata up to 2019-11-05"
        content_type: "erratum"
        inclusion_type: "true"
        original_packages: "false"
        date_type: "issued"
        end_date: "2019-11-05"
    third_filter:
      - name: "Errata up to 2020-04-28"
        content_type: "erratum"
        inclusion_type: "true"
        original_packages: "false"
        date_type: "issued"
        end_date: "2020-04-28"
    filter_repos: "Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs),Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)"

  tasks:
  - name: "set content repositories"
    include_tasks: set_repos.yml
    loop: "{{ content_repos }}"

  - name: "check repo synch status"
    ansible.builtin.command: >
      hammer product list 
      --organization "{{ organization }}"
      --name "Red Hat Enterprise Linux for x86_64"
      --fields "Sync state"
    register: synch_status

#  - name: "synch content repositories"
#    include_tasks: synch_content_repo.yml
#    loop: "{{ content_repos }}"
#    when: "'Running' not in synch_status.stdout"

  - name: "create lifecycle environments"
    include_tasks: set_lifecycle_envs.yml
    loop: "{{ lifecycle_envs }}"

  - name: "create content view"
    include_tasks: create_content_view.yml

  - name: "create first filter"
    include_tasks: create_filter.yml
    loop: "{{ first_filter }}"