---

- name: "Install connected satellite server"
  hosts: all
  gather_facts: no
  vars:
    content_repos:
      - "Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)"
      - "Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)"
      - "Red Hat Satellite Tools 6.10 for RHEL 8 x86_64 (RPMs)"

  tasks:
  - name: "checking for manifest file on /data (satellite media volume)"
    ansible.builtin.stat:
      path: "/data/{{ manifest_zip_file }}"
    register: data

  - name: "manage subscription upload"
    block:
      - name: "checking for existing subscription upload"
        ansible.builtin.command: >
          hammer subscription list
          --organization "Emergent"
        register: sub
        changed_when: no

      - name: "importing manifest file"
        ansible.builtin.command: >
          hammer subscription upload
          --file /data/"{{ manifest_zip_file }}"
          --organization "Emergent"
        when: "'Red Hat Enterprise Linux' not in sub.stdout"
    become: yes
    when: data.stat.exists

  - name: "set content repositories"
    include_tasks: set_repos.yml
    loop: "{{ content_repos }}"

  - name: "synch content repositories"
    ansible.builtin.command: >
      hammer repository synchronize
      --product "Red Hat Enterprise Linux for x86_64"
      --name "{{ item }}"
      --organization-label "Emergent"
      --async
    loop: "{{ content_repos }}"
    become: yes