---

- name: "Install connected satellite server"
  hosts: all
  become: yes
  gather_facts: no
  vars:
    product: "Red Hat Enterprise Linux for x86_64"
    organization: "Emergent"
    cv_name: "RHEL8"
    content_repos:
      - set_name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)"
        synch_name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8"
      - set_name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)"
        synch_name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8"
      - set_name: "Red Hat Satellite Tools 6.10 for RHEL 8 x86_64 (RPMs)"
        synch_name: "Red Hat Satellite Tools 6.10 for RHEL 8 x86_64 RPMs"
    lifecycle_envs:
      - name: Development
        prior: Library
      - name: Production
        prior: Development
    ak_prod:
      - name: rhel8_prod
        cv: RHEL8
        lc: Production

  tasks:
  - name: "checking for manifest file on /data (satellite media volume)"
    ansible.builtin.stat:
      path: "/data/{{ manifest_zip_file }}"
    register: data

  - name: "manage subscription upload"
    block:
      - name: "checking for existing subscription upload"
        ansible.builtin.command: >
          hammer subscription list
          --organization "{{ organization }}"
        register: sub
        changed_when: no

      - name: "importing manifest file"
        ansible.builtin.command: >
          hammer subscription upload
          --file /data/"{{ manifest_zip_file }}"
          --organization "{{ organization }}"
        when: "'Red Hat Enterprise Linux' not in sub.stdout"
    when: data.stat.exists

  - name: "set content repositories"
    include_tasks: set_repos.yml
    loop: "{{ content_repos }}"

  - name: "synch content repositories"
    ansible.builtin.command: >
      hammer repository synchronize
      --product "Red Hat Enterprise Linux for x86_64"
      --name "{{ item.synch_name }}"
      --organization "{{ organization }}"
      --async
    loop: "{{ content_repos }}"
    when: false

  - name: "create lifecycle environments"
    include_tasks: set_lifecycle_envs.yml
    loop: "{{ lifecycle_envs }}"

  - name: "get repo ids"
    ansible.builtin.shell: >
      hammer repository list |
      grep "{{ product }}" | 
      awk '{printf "%s%s",sep,$1; sep=","} END{print ""}'
    register: rep_list
    changed_when: false

  - name: "list content views"
    ansible.builtin.command: >
      hammer content-view list
    register: cv_list
    changed_when: false

  - name: "create content view"
    ansible.builtin.command: >
      hammer content-view create
      --name "{{ cv_name }}"
      --repository-ids "{{ rep_list.stdout }}"
      --organization "{{ organization }}"
    when: "cv_name not in cv_list.stdout"

  - name: "get content view id"
    ansible.builtin.shell: >
      hammer content-view list |
      grep "{{ cv_name }}" |
      awk '{printf "%s%s",sep,$1; sep=","} END{print ""}'
    register: cv_ID
    changed_when: false

  - name: "get version list"
    ansible.builtin.shell: >
      hammer content-view version list |
      grep "{{ cv_name }}" |
      awk -F'|' '{gsub(" ",""); print $3}'
    register: cv_ver_list
    changed_when: false

  - name: "publish content view"
    ansible.builtin.command: >
      hammer content-view publish
      --id "{{ cv_ID.stdout | int }}"
      --major 1
      --minor 0
      --organization "{{ organization }}"
      --async
    when: (cv_ID.stdout|length > 0) and 
          (cv_ver_list.stdout|length == 0)

  - name: "get version lifecycle envs"
    ansible.builtin.shell: >
      hammer content-view version list |
      grep "{{ cv_name }}" |
      awk -F'|' '{print $5}'
    register: cv_ver_envs
    changed_when: false

  - name: "promote content view"
    ansible.builtin.command: >
      hammer content-view version promote
      --content-view "{{ cv_name }}"
      --to-lifecycle-environment "{{ item.name }}"
      --organization "{{ organization }}"
      --async
    loop: "{{ lifecycle_envs }}"
    when: "item.name not in cv_ver_envs.stdout"

  - name: "list prod activation key"
    ansible.builtin.shell: >
      hammer activation-key list \
      --organization "{{ organization }}" |
      grep "{{ ak_prod }}" 
    register: ak_prod_list
    changed_when: false

  - name: "create prod activatino key"
    ansible.builtin.command: >
      hammer activation-key create
      --name "{{ ak_prod.name }}"
      --content-view "{{ ak_prod.cv }}"
      --lifecycle-environment "{{ ak_prod.lc }}"
      --organization "{{ organization }}"
    when: "ak_prod.name not in ak_prod_list.stdout"  