---

- name: "Install connected satellite server"
  hosts: all
  gather_facts: no
    
  tasks:
  - name: "checking for manifest file on /data (satellite media volume)"
    ansible.builtin.stat:
      path: "/data/{{ manifest_zip_file }}"
    register: data

  - name: "manage subscription upload"
    block:
      - name: "checking for existing subscription upload"
        ansible.builtin.command: >
          hammer subscription list
          --organization "Emergent"
        register: sub

      - name: "importing manifest file"
        ansible.builtin.command: >
          hammer subscription upload
          --file /data/"{{ manifest_zip_file }}"
          --organization "Emergent"
        when: "'Red Hat Enterprise Linux' not in sub.stdout"
    become: yes
    when: data.stat.exists
