---
- name: "get repo ids"
  ansible.builtin.shell: >
    hammer repository list |
    grep "{{ product }}" | 
    awk '{printf "%s%s",sep,$1; sep=","} END{print ""}'
  register: rep_list
  changed_when: false

- name: "list content views"
  ansible.builtin.command: >
    hammer content-view list
  register: cv_list
  changed_when: false

- name: "create content view"
  ansible.builtin.command: >
    hammer content-view create
    --name "{{ cv_name }}"
    --repository-ids "{{ rep_list.stdout }}"
    --organization "{{ organization }}"
  when: "cv_name not in cv_list.stdout"

