---

- name: "create_satellite_dns"
  hosts: all
  gather_facts: no
    
  tasks:
    - name: get server public ip
      amazon.aws.ec2_instance_info:
        region: "{{ ec2_region }}"
        filters: 
          "tag:Name": "{{ ec2_name_prefix }} {{ tier }} Satellite Server*"
      register: ec2_info

    - debug:
        var: ec2_info.instances[0].public_ip_address

