---
- name: "create filter"
  ansible.builtin.command: >
    hammer content-view filter create
    --name "{{ item.name }}"
    --type "{{ item.content_type }}"
    --content-view "{{ cv_name }}"
    --description "{{ item.name }}"
    --inclusion "{{ item.inclusion_type }}"
    --organization "{{ organization }}"
    --repositories "{{ filter_repos }}"
    --product "{{ product }}"
    --original-packages "{{ item.original_packages }}"

- name: "create filter rule"
  ansible.builtin.command: >
    hammer content-view filter rule create
    --content-view "{{ cv_name }}"
    --content-view-filter "{{ item.name }}"
    --date-type "{{ item.date_type | default(omit) }}"
    --end-date "{{ item.end_date | default(omit) }}"





