---

- name: "Install disconnected satellite server"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: remove amazon rhui client
    command: yum -y remove rh-amazon-rhui-client*
    args:
      warn: false

  - name: clear repo config
    command: rm -rf /etc/yum.repos.d/*
    args:
      warn: false

  - name: copy product-id.conf
    file:
      src: product-id.conf
      dest: /etc/yum/pluginconf.d/product-id.conf
    
  - name: make media mount points
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    loop:
      - /media/rhel7-server
      - /media/sat6

  - name: mount rhel server iso
    ansible.posix.mount:
      path: /media/rhel7-server
      src: /data/rhel-server-7.9-x86_64-dvd.iso
      fstype: iso9660
      opts: loop
      state: present

  - name: mount satellite iso
    ansible.posix.mount:
      path: /media/sat6
      src: /data/satellite-6.9.6.1-rhel-7-x86_64-dvd.iso
      fstype: iso9660
      opts: loop
      state: present
