---

- name: "Install disconnected satellite server"
  hosts: all
  gather_facts: no
    
  tasks:
  - name: remove amazon rhui client
    command: yum -y remove rh-amazon-rhui-client*
    args:
      warn: false
    become: yes

  - name: clear repo config
    command: rm -rf /etc/yum.repos.d/*
    args:
      warn: false
    become: yes

  - name: copy product-id.conf
    file:
      src: product-id.conf
      dest: /etc/yum/pluginconf.d/product-id.conf
    become: yes
    
  - name: make media mount points
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    loop:
      - /media/rhel7-server
      - /media/sat6
    become: yes
