---

- name: "Install disconnected satellite server"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: remove amazon rhui client
    yum:
      name: rh-amazon-rhui-client*
      state: absent

  - name: clear repo config
    file: 
      name: /etc/yum.repos.d/*
      state: absent

  - name: copy product-id.conf
    copy:
      src: product-id.conf
      dest: /etc/yum/pluginconf.d/product-id.conf
    
  - name: make media mount points
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    loop:
      - /media/rhel7-server
      - /media/sat6

  - name: mount rhel server iso
    ansible.posix.mount:
      path: /media/rhel7-server
      src: /data/rhel-server-7.9-x86_64-dvd.iso
      fstype: iso9660
      opts: loop
      state: mounted

  - name: mount satellite iso
    ansible.posix.mount:
      path: /media/sat6
      src: /data/satellite-6.9.6.1-rhel-7-x86_64-dvd.iso
      fstype: iso9660
      opts: loop
      state: mounted

  - name: copy media.repo
    copy:
      src: /media/rhel7-server/media.repo
      dest: /etc/yum.repos.d/rhel7-server.repo
      remote_src: yes

  - name: add baseurl to repo
    lineinfile:
      path: /etc/yum.repos.d/rhel7-server.repo
      line: 'baseurl=file:///media/rhel7-server/'

  - name: update and reboot
    yum:
      update_cache: yes
      name: "*"
      state: latest

  - name: Check for reboot needed
    command: /usr/bin/needs-restarting -r
    register: needs_reboot
    ignore_errors: yes
    failed_when: needs_reboot.rc >= 2
    changed_when: needs_reboot.rc == 1

  - name: Reboot if necessary
    reboot:
    when: needs_reboot.rc == 1

  - name: Find all rpm files in deps folder
    find:
      paths: "/data/deps"
      patterns: "*.rpm"
    register: rpm_files
  
  - name: Setting rpm_list
    set_fact:
      rpm_list: "{{ rpm_files.files | map(attribute='path') | list}}"

  - name: installing the rpm files
    yum:
      name: "{{rpm_list}}"
      state: present

  - name: install satellite packages
    command:
      cmd: /media/sat6/install_packages
      chdir: /media/sat6

