- name: "Manage satellite media volume"
  hosts: all
  gather_facts: no
  vars:
    ec2_region: us-east-1

  tasks:
  - name: get volume info
    amazon.aws.ec2_vol_info:
      region: "{{ ec2_region }}"
      filters:
        "tag:Name": satellite-media
    register: vol_info

  - name: get public instance info
    ec2_instance_info:
      region: "{{ ec2_region }}"
      filters:
        "tag:Name": "*Satellite Server*"
        "tag:Tier": "Public"
    register: public instance_info

  - name: get private instance info
    ec2_instance_info:
      region: "{{ ec2_region }}"
      filters:
        "tag:Name": "*Satellite Server*"
        "tag:Tier": "Private"
    register: private_instance_info

