- name: "Manage satellite media volume"
  hosts: all
  gather_facts: no
  vars:
    region: us-east-1
      
  tasks:
  - name: get volume info
    amazon.aws.ec2_vol_info:
      filters:
        "tag:Name": satellite-media
    register: vol_info

