- name: "Manage satellite media volume"
  hosts: all
  gather_facts: no
  vars:
    ec2_region: us-east-1

  tasks:
  - name: get volume info
    amazon.aws.ec2_vol_info:
      region: "{{ ec2_region }}"
      filters:
        "tag:Name": satellite-media
    register: vol

  - name: detach volume
    amazon.aws.ec2_vol:
      region: "{{ ec2_region }}"
      instance: None
      id: "{{ vol.volumes[0].id }}"

  - name: get instance info
    ec2_instance_info:
      region: "{{ ec2_region }}"
      filters:
        "tag:Name": "*Satellite Server*"
        "tag:Tier": "{{ tier }}"
    register: instance

  - name: attach volume to instance
    amazon.aws.ec2_vol:
      region: "{{ ec2_region }}"
      instance: "{{ instance.instances[0].instance_id }}"
      id: "{{ vol.volumes[0].id }}"
