- name: "Manage satellite media volume"
  hosts: all
  gather_facts: no
  vars:
    ec2_region: us-east-1

  tasks:
  - name: get volume info
    amazon.aws.ec2_vol_info:
      region: "{{ ec2_region }}"
      filters:
        "tag:Name": satellite-media
    register: vol

  - name: get public instance info
    ec2_instance_info:
      region: "{{ ec2_region }}"
      filters:
        "tag:Name": "*Satellite Server*"
        "tag:Tier": "Public"
    register: public_instance

  - name: get private instance info
    ec2_instance_info:
      region: "{{ ec2_region }}"
      filters:
        "tag:Name": "*Satellite Server*"
        "tag:Tier": "Private"
    register: private_instance

  - name: attach volume to public instance
    amazon.aws.ec2_vol:
      region: "{{ ec2_region }}"
      instance: "{{ public_instance.instances[0].instance_id }}"
      id: "{{ vol.volumes[0].id }}"
