---
- name: "get"
  hosts: tag_Platform_Satellite
  gather_facts: no
  become: yes
  tasks:
  - name: "get registration command"
    ansible.builtin.command:
      hostname
    delegate_to: "{{ item }}"
    register: reg_command
    loop: "{{ groups['tag_Platform_Satellite'] }}"


- name: "register satellite clients"
  hosts: tag_Platform_RHEL
  gather_facts: no
  become: yes

  tasks:
  - name: "remove rhui"
    ansible.builtin.yum:
      name: rh-amazon-rhui-client*
      state: absent

  - name: "start rhsmcertd"
    ansible.builtin.systemd:
      name: rhsmcertd
      enabled: yes
      state: started

