---

- name: "register satellite clients"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: "get registration command"
    ansible.builtin.command:
      hostname
    register: reg_command
    delegate_to: "{{ groups['tag_Platform_Satellite'] }}"

  - name: "remove rhui"
    ansible.builtin.yum:
      name: rh-amazon-rhui-client*
      state: absent

  - name: "start rhsmcertd"
    ansible.builtin.systemd:
      name: rhsmcertd
      enabled: yes
      state: started

