---
- name: "get"
  hosts: tag_Platform_Satellite
  gather_facts: no
  become: yes
  vars:


  tasks:
  - name: "get registration command"
    ansible.builtin.command: >
      hammer host-registration generate-command
      -–insecure yes 
      --activation-key rhel8_prod 
      --organization Emergent 
      --location "Virginia Beach" -
      -lifecycle-environment "Production" 
      --update-packages no
    register: reg_command

  - name: "print command"
    debug:
      var: reg_command

- name: "register satellite clients"
  hosts: tag_Platform_RHEL
  gather_facts: no
  become: yes

  tasks:
  - name: "remove rhui"
    ansible.builtin.yum:
      name: rh-amazon-rhui-client*
      state: absent

  - name: "start rhsmcertd"
    ansible.builtin.systemd:
      name: rhsmcertd
      enabled: yes
      state: started

