---
- name: "checking for existing lifecycle {{ item.name }}"
  ansible.builtin.command: >
    hammer lifecycle-environment list
    --organization "Emergent"
    --name "{{ item.name }}"
  register: list
  changed_when: no
  become: yes

- name: "setting lifecycle {{ item.name }}"
  ansible.builtin.command: >
      hammer lifecycle-environment create
      --name "{{ item.name }}"
      --prior "{{ item.prior }}"
      --organization "Emergent"
  when: "item.name not in list.stdout"
  become: yes
