---
- name: "checking for existing repo set"
  ansible.builtin.command: >
    hammer repository-set list
    --organization "Emergent"
    --name "{{ item.set_name }}"
    --enabled true
  register: list
  changed_when: no
  become: yes

- name: "setting repo"
  ansible.builtin.command: >
    hammer repository-set enable
    --organization "Emergent"
    --name "{{ item.set_name }}"
    --releasever "8"
  when: "'Red Hat' not in list.stdout"
  become: yes
