---

- name: "show satellite settings"
  hosts: all
  gather_facts: yes

  tasks:
  - name: Multiple environment​ variables in a single line ansible task
    debug:
      msg: "{{ lookup('env','*') }}"

