---

- name: "show satellite settings"
  hosts: all
  gather_facts: no

  tasks:
  - name: "Show a setting"
    redhat.satellite.setting_info:
      username: "sat_admin"
      password: "emergent"
      server_url: "https://ec2-3-208-28-141.compute-1.amazonaws.com"
      name: "http_proxy"

