---

- name: "show satellite settings"
  hosts: all
  gather_facts: no

  tasks:
  - name: "show settings"
    ansible.builtin.stat:
      path: /data/manifest_connected_satellite_demo_20211117T143322Z.zip
    register: data

  - name: print debug
    ansible.builtin.debug:
      var: data