---

- name: "show satellite settings"
  hosts: all
  gather_facts: no

  tasks:
  - name: "Show a setting"
    redhat.satellite.setting_info:
      username: "admin"
      password: "changeme"
      server_url: "https://satellite.example.com"
      name: "http_proxy"

