---
- name: "check repo synch status"
  ansible.builtin.command: >
    hammer product list 
    --product "Red Hat Enterprise Linux for x86_64"
    --name "{{ item.synch_name }}"
    --organization "{{ organization }}"
  register: synch_status

- debug:
    var: synch_status.stdout

- name: "synch content repositories"
  ansible.builtin.command: >
    hammer repository synchronize
    --product "Red Hat Enterprise Linux for x86_64"
    --name "{{ item.synch_name }}"
    --organization "{{ organization }}"
    --async
  become: yes
