---
- name: "synch content repo {{ item.synch_name }}"
  ansible.builtin.command: >
    hammer repository synchronize
    --product "Red Hat Enterprise Linux for x86_64"
    --name "{{ item.synch_name }}"
    --organization "{{ organization }}"
    --async
  become: yes
